# Modified from BlueBuild template — exonomos
name: ucore
description: Custom uCore server OS
base-image: ghcr.io/ublue-os/ucore
image-version: stable

modules:
  - type: files
    files:
      - source: etc
        destination: /etc

  - type: rpm-ostree
    install:
      - neovim
      - dracut-sshd
      - ansible-core
      - git
      - rsync

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - create-swapfile.service
        - tailscaled.service
        - var-swapfile.swap
        - ansible-pull.timer
        - podman-prune.timer
      disabled:
        - zincati.service
      masked:
        - zincati.service
        - rpm-ostree-countme.timer

  - type: script
    snippets:
      - "ansible-galaxy collection install ansible.posix -p /usr/share/ansible/collections"
